smtp:
  CharSet: 'utf-8'
  delivery_method: :smtp
  enable_starttls_auto: true
  host: 'smtp.mail.ru'
  SMTPAuth: true
  authentication: :login
  username: 'cityforall@mail.ru'
  password: 'abumed00'
  SMTPSecure: 'ssl'
  Port: 465
